### ISSUE TITLE
Requirement.txt installation crashes.

### ISSUE THREAD

**Issue by GregBorrelly** [mdezube/sms-analysis#11]
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

After running sudo pip install -r requirements.txt

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'

**Comment by mdezube** [comment]
This is an issue with pip, not with this package.  Try running `pip install --user -r requirements.txt` and let me know if that works for you.

Also, what OS are you running?

**Comment by BacksSlash092** [comment]
Will try as soon as I get home. Great talk by the way. It was my first meet up and I feel like learned so much. 

My computers all run Linux but my girlfriend uses a MacBook so I'm using hers.

The OS version on the mac is
OSX

**Comment by GregBorrelly** [comment]
Will try as soon as I get home. Great talk by the way. It was my first meet up and I feel like learned so much.

My computers all run Linux but my fiance uses a MacBook so I'm using hers.

The OS version on the mac is
 OSX

I submitted an issue to [pip](https://github.com/pypa/pip/issues/4244) to fix the issue, or hopefully they can point me on a direction to fix the issue(This seems like a cool learning exercise)

I also came a cross another answer while doing research, and that is to create a virtual environment, and then proceed with the installation. 

I will try both  pip install --user -r requirements.txt   and the virtual environment solutions, and let you know how they turn out.

**Comment by mdezube** [comment]
If you go the virtual environment route, use anaconda, that's the standard at this point.  It'll definitely solve your issue.  Then circle back here to let me know what works!  I'll update the README according.

Also very glad to hear you enjoyed the talk :)  I very much enjoyed the audience engagement!
